import React from "react";
import "./Dashboard.css";

function Dashboard() {
  return (
    <div className="dashboard">
      <h1>DASHBOARD</h1>

      <table>
        <tr>
          <th>Name</th>
          <th>Phone Number</th>
          <th>Email Address</th>
          <th>Offer</th>
        </tr>
        <tr>
          <td>Jill</td>
          <td>+157629977027</td>
          <td>admin@outlook.com</td>
          <td>Pending</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>+2347373890</td>
          <td>admin@outlook.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>07013673992</td>
          <td>delan@microsoft.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Jill</td>
          <td>+157629977027</td>
          <td>admin@outlook.com</td>
          <td>Pending</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>+2347373890</td>
          <td>admin@outlook.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>07013673992</td>
          <td>delan@microsoft.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Jill</td>
          <td>+157629977027</td>
          <td>admin@outlook.com</td>
          <td>Pending</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>+2347373890</td>
          <td>admin@outlook.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>07013673992</td>
          <td>delan@microsoft.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Jill</td>
          <td>+157629977027</td>
          <td>admin@outlook.com</td>
          <td>Pending</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>+2347373890</td>
          <td>admin@outlook.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>07013673992</td>
          <td>delan@microsoft.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Jill</td>
          <td>+157629977027</td>
          <td>admin@outlook.com</td>
          <td>Pending</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>+2347373890</td>
          <td>admin@outlook.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>07013673992</td>
          <td>delan@microsoft.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Jill</td>
          <td>+157629977027</td>
          <td>admin@outlook.com</td>
          <td>Pending</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>+2347373890</td>
          <td>admin@outlook.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>07013673992</td>
          <td>delan@microsoft.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Jill</td>
          <td>+157629977027</td>
          <td>admin@outlook.com</td>
          <td>Pending</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>+2347373890</td>
          <td>admin@outlook.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>07013673992</td>
          <td>delan@microsoft.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Jill</td>
          <td>+157629977027</td>
          <td>admin@outlook.com</td>
          <td>Pending</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>+2347373890</td>
          <td>admin@outlook.com</td>
          <td>Attended</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>07013673992</td>
          <td>delan@microsoft.com</td>
          <td>Attended</td>
        </tr>
      </table>
    </div>
  );
}

export default Dashboard;
